main: fr.peaceandcube.pacfirstplayed.PACFirstPlayed
name: PACFirstPlayed
description: A plugin showing the date you joined the server
version: ${version}
author: YanisBft
website: https://github.com/PeaceAndCubeMC/PACFirstPlayed
api-version: 1.19

commands:
  firstplayed:
    description: Shows when you joined the server
    aliases: fp
    permission: peaceandcube.firstplayed.me
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/firstplayed [<player>]"
  fpdate:
    description: Shows who joined the server on a date
    permission: peaceandcube.fpdate
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/fpdate <date>"
  pacfirstplayed:
    description: Reloads the plugin
    permission: peaceandcube.pacfirstplayed
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/pacfirstplayed reload"

permissions:
  peaceandcube.firstplayed.me:
    description: Allows you to get your own join date
    default: op
  peaceandcube.firstplayed.other:
    description: Allows you to get another player join date
    default: op
  peaceandcube.fpdate:
    description: Allows to see who joined the server on a date
    default: op
  peaceandcube.pacfirstplayed:
    description: Allows you to use /pacfirstplayed command
    default: op
